=== SonOfViktor/XMLParsing/resources/data/papers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns = "http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.fairycompany.com/papers"
        xmlns:tns="http://www.fairycompany.com/papers"
        elementFormDefault="qualified">

    <element name="paper" type="tns:Paper" abstract="true"/>
    <element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:paper"/>
    <element name="magazine" type = "tns:Magazine" substitutionGroup="tns:paper"/>
    <element name = "papers">
        <complexType>
            <sequence>
                <element ref = "tns:paper"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Paper">
        <sequence>
            <element name="name" type="string"/>
            <element name="subscription-index" type = "tns:IndexID"/>
            <element name="issue" type="positiveInteger"/>
            <element name="pages" type="positiveInteger"/>
            <element name="price">
                <simpleType>
                    <restriction base="double">
                        <minExclusive value="0.0"/>  <!-- Разобраться -->
                    </restriction>
                </simpleType>
            </element>
            <element name="issue-date" type="date"/>
            <element name="circulation" type="positiveInteger"/>
        </sequence>
        <attribute name="website" type="tns:WebsiteID" use = "optional" default = "no site"/>
        <attribute name="age-category" use = "required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="adult"/>
                    <enumeration value="child"/>
                    <enumeration value="teenager"/>
                    <enumeration value="anyone"/>
                </restriction>
            </simpleType>
        </attribute>

    </complexType>

    <complexType name="Newspaper">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="color" type="boolean"/>
                    <element name="frequency">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="daily"/>
                                <enumeration value="weekly"/>
                                <enumeration value="monthly"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Magazine">
        <complexContent>
            <extension base="tns:Paper">
                <sequence>
                    <element name="direction" type = "tns:Direction"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name = "IndexID">
        <restriction base = "ID">
            <pattern value = "i\d{1,6}"/>
        </restriction>
    </simpleType>

    <simpleType name = "WebsiteID">
        <restriction base = "ID">
            <pattern value = "www\.\w{2,20}\.[a-z]{2,4}"/>
        </restriction>
    </simpleType>

    <simpleType name="Direction">
        <restriction base="string">
            <enumeration value="sport"/>
            <enumeration value="gaming"/>
            <enumeration value="erotic"/>
            <enumeration value="entertainment"/>
            <enumeration value="science"/>
            <enumeration value="training"/>
            <enumeration value="health"/>
        </restriction>
    </simpleType>

</schema>

=== SonOfViktor/XMLParsing/resources/testdata/papers.xml
<?xml version="1.0" encoding="UTF-8" ?>

<papers xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xmlns ="http://www.fairycompany.com/papers"
        xsi:schemaLocation = "http://www.fairycompany.com/papers papers.xsd">

    <newspaper age-category="anyone" website="www.aif.by">
        <name>Аиф</name>
        <subscription-index>i13137</subscription-index>
        <paper-properties>
            <issue>1503</issue>
            <pages>100</pages>
            <price>3.50</price>
            <issue-date>2021-06-16</issue-date>
        </paper-properties>
        <circulation>60000</circulation>
        <color>true</color>
        <frequency>daily</frequency>
    </newspaper>

    <newspaper age-category="adult">
        <name>СБ</name>
        <subscription-index>i00001</subscription-index>
        <paper-properties>
            <issue>1503</issue>
            <pages>100</pages>
            <price>3.50</price>
            <issue-date>2021-06-16</issue-date>
        </paper-properties>
        <circulation>25000</circulation>
        <color>false</color>
        <frequency>weekly</frequency>
    </newspaper>

    <magazine age-category="teenager">
        <name>Cool</name>
        <subscription-index>i20056</subscription-index>
        <paper-properties>
            <issue>1503</issue>
            <pages>100</pages>
            <price>3.50</price>
            <issue-date>2021-06-16</issue-date>
        </paper-properties>
        <circulation>43000</circulation>
        <direction>entertainment</direction>
    </magazine>

    <magazine age-category="child" website="www.igromania.ru">
        <name>Игромания</name>
        <subscription-index>i76398</subscription-index>
        <paper-properties>
            <issue>1503</issue>
            <pages>100</pages>
            <price>3.50</price>
            <issue-date>2021-06-16</issue-date>
        </paper-properties>
        <circulation>180000</circulation>
        <direction>gaming</direction>
    </magazine>
</papers>

=== SonOfViktor/XMLParsing/resources/data/papers.xml
<?xml version="1.0" encoding="UTF-8" ?>

<papers xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xmlns ="http://www.fairycompany.com/papers"
        xsi:schemaLocation = "http://www.fairycompany.com/papers papers.xsd">

    <newspaper age-category="anyone" website="www.sb.by">
        <name>Советская Беларусь</name>
        <subscription-index>i45891</subscription-index>
        <paper-properties>
            <issue>1814</issue>
            <pages>22</pages>
            <price>3.25</price>
            <issue-date>2021-06-07</issue-date>
        </paper-properties>
        <circulation>50000</circulation>
        <color>false</color>
        <frequency>daily</frequency>
    </newspaper>

    <newspaper age-category="anyone" website="www.aif.by">
        <name>Аргументы И Факты</name>
        <subscription-index>i13137</subscription-index>
        <paper-properties>
            <issue>1540</issue>
            <pages>28</pages>
            <price>2.60</price>
            <issue-date>2021-05-04</issue-date>
        </paper-properties>
        <circulation>60000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper  website="www.vitbichi.by" age-category="anyone">
        <name>Вiтьбiчы</name>
        <subscription-index>i78013</subscription-index>
        <paper-properties>
            <issue>3804</issue>
            <pages>16</pages>
            <price>1.45</price>
            <issue-date>2021-05-28</issue-date>
        </paper-properties>
        <circulation>17000</circulation>
        <color>true</color>
        <frequency>daily</frequency>
    </newspaper>

    <newspaper age-category="adult">
        <name>Детективная Газета</name>
        <subscription-index>i15038</subscription-index>
        <paper-properties>
            <issue>1028</issue>
            <pages>28</pages>
            <price>3.70</price>
            <issue-date>2021-06-02</issue-date>
        </paper-properties>
        <circulation>55000</circulation>
        <color>true</color>
        <frequency>monthly</frequency>
    </newspaper>

    <newspaper age-category="teenager">
        <name>Знамя Юности</name>
        <subscription-index>i18403</subscription-index>
        <paper-properties>
            <issue>780</issue>
            <pages>20</pages>
            <price>1.70</price>
            <issue-date>2021-05-28</issue-date>
        </paper-properties>
        <circulation>12000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="anyone">
        <name>Навука</name>
        <subscription-index>i17038</subscription-index>
        <paper-properties>
            <issue>386</issue>
            <pages>28</pages>
            <price>2.80</price>
            <issue-date>2021-06-02</issue-date>
        </paper-properties>
        <circulation>15000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="anyone">
        <name>Вяжем шьем вышиваем</name>
        <subscription-index>i19025</subscription-index>
        <paper-properties>
            <issue>487</issue>
            <pages>36</pages>
            <price>4.00</price>
            <issue-date>2021-06-02</issue-date>
        </paper-properties>
        <circulation>18000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <newspaper age-category="teenager" website="www.pvz.by">
        <name>Переходный возраст</name>
        <subscription-index>i63192</subscription-index>
        <paper-properties>
            <issue>780</issue>
            <pages>40</pages>
            <price>4.20</price>
            <issue-date>2021-06-03</issue-date>
        </paper-properties>
        <circulation>18000</circulation>
        <color>true</color>
        <frequency>weekly</frequency>
    </newspaper>

    <magazine age-category="anyone" website="www.igromania.ru">
        <name>Игромания</name>
        <subscription-index>i76398</subscription-index>
        <paper-properties>
            <issue>1548</issue>
            <pages>208</pages>
            <price>20.00</price>
            <issue-date>2021-06-08</issue-date>
        </paper-properties>
        <circulation>180000</circulation>
        <direction>gaming</direction>
    </magazine>

    <magazine age-category="anyone">
        <name>Speak English</name>
        <subscription-index>i87954</subscription-index>
        <paper-properties>
            <issue>450</issue>
            <pages>110</pages>
            <price>18.00</price>
            <issue-date>2021-05-11</issue-date>
        </paper-properties>
        <circulation>28000</circulation>
        <direction>training</direction>
    </magazine>

    <magazine age-category="adult">
        <name>Playboy</name>
        <subscription-index>i18390</subscription-index>
        <paper-properties>
            <issue>3548</issue>
            <pages>115</pages>
            <price>23.00</price>
            <issue-date>2021-06-01</issue-date>
        </paper-properties>
        <circulation>240000</circulation>
        <direction>erotic</direction>
    </magazine>

    <magazine age-category="child">
        <name>Мурзилка</name>
        <subscription-index>i12380</subscription-index>
        <paper-properties>
            <issue>511</issue>
            <pages>32</pages>
            <price>6.50</price>
            <issue-date>2021-05-28</issue-date>
        </paper-properties>
        <circulation>32000</circulation>
        <direction>entertainment</direction>
    </magazine>

    <magazine age-category="teenager">
        <name>Cool</name>
        <subscription-index>i20056</subscription-index>
        <paper-properties>
            <issue>1548</issue>
            <pages>63</pages>
            <price>8.50</price>
            <issue-date>2021-06-08</issue-date>
        </paper-properties>
        <circulation>43000</circulation>
        <direction>entertainment</direction>
    </magazine>

    <magazine website="www.bolshoisport.ru" age-category="anyone" >
        <name>Большой Спорт</name>
        <subscription-index>i12354</subscription-index>
        <paper-properties>
            <issue>240</issue>
            <pages>150</pages>
            <price>17.00</price>
            <issue-date>2021-06-02</issue-date>
        </paper-properties>
        <circulation>70000</circulation>
        <direction>sport</direction>
    </magazine>

    <magazine age-category="anyone">
        <name>Народный доктор</name>
        <subscription-index>i14567</subscription-index>
        <paper-properties>
            <issue>580</issue>
            <pages>98</pages>
            <price>12.00</price>
            <issue-date>2021-06-02</issue-date>
        </paper-properties>
        <circulation>70000</circulation>
        <direction>health</direction>
    </magazine>

    <magazine age-category="anyone" website="www.internauka.org">
        <name>Интернаука</name>
        <subscription-index>i45781</subscription-index>
        <paper-properties>
            <issue>360</issue>
            <pages>68</pages>
            <price>23.50</price>
            <issue-date>2021-06-08</issue-date>
        </paper-properties>
        <circulation>280000</circulation>
        <direction>science</direction>
    </magazine>
</papers>
